### ISSUE TITLE
项目加载报错

### ISSUE THREAD

**Issue by diddowill** [feiniaojin/ddd-cms#1]
在Idea中加载项目报错：
Unresolved dependency: 'com.feiniaojin:ddd:jar:1.0-SNAPSHOT'
上面的SNAPSHOT包是在私有仓库中？

**Comment by feiniaojin** [comment]
在这里，https://github.com/feiniaojin/ddd

**Comment by feiniaojin** [comment]
系统提示:您的邮件被腾讯邮箱判定为垃圾邮件,请编辑后重新发送!
